<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Uml4Net.Codex.MetamodelGen\Uml4Net.Codex.MetamodelGen.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**\*.xmi" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
